apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: my-service
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ahanson1/backend:backend
        imagePullPolicy: "Always"
        ports:
        - containerPort: 5001
        env:
        - name: DATABASE_URI
          value: mysql+pymysql://dbProject:dB4a15!4@terraform-20201120185648962100000002.clh36ghk8zgg.eu-west-1.rds.amazonaws.com:3306/users