apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: my-service
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ahanson1/frontend:frontend
        ports:
        - containerPort: 5000