---
- hosts: all
  become: true
  tasks:
    - name: "Download and install Docker"
      script: ~/tf_project/Install_Scripts/install_docker.sh

    - name: "Download and install Jenkins"
      script: ~/tf_project/Install_Scripts/install_jenkins.sh

    - name: "Download and install Kubectl"
      script: ~/tf_project/Install_Scripts/install_kubectl.sh